Cameras:
  - type: "AdafruitPTC08"
  - type: "AdafruitPTC08"
  - type: "MockCamera"
    filename: "res/positions/"
IMUs:
  - type: "HCrestFSM300"
  - type: "HCrestFSM300"
Motors:
  - type: "ServoMG996R"
  - type: "ServoMG996R"
  - type: "ServoMG996R"
Model:
  - type: "Lagragian"
StateEstimator:
  type: "UnscentedKalmanFilter"
Engine:
  type: "UCIEngine"
  tt_size: 16 # in MB
  threads: 1
PathPlanningAlg:
  type: "B-Splines"
Controller:
  type: "GravityCompPID"
Recognition:
  type: "SegmentClassify"
